# Following this instructions https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -list -project BeAware.xcodeproj && xcodebuild -scheme BeAware -configuration Debug build
#     - name: Run tests
#       run: swift test -v
