name: Xcode Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-12
#     macos-latest uses macos-11 as of november 2022 which doesn't have Xcode 14

    steps:
    - uses: actions/checkout@v3
    - name: Build
# For help run: xcodebuild -list -project BeAware.xcodeproj && xcode-select --version && softwareupdate --history && which xcodebuild && xcodebuild -scheme BeAware -configuration Debug -sdk iphonesimulator build
      run: xcodebuild -scheme BeAware -configuration Debug -sdk iphonesimulator build

# Figured out using these links
# https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
# https://developer.apple.com/forums/thread/659152 
# https://gist.github.com/fabianfett/fd811d7921eb856bb100c5c15565077f?permalink_comment_id=3517740#gistcomment-3517740 
# https://stackoverflow.com/questions/21272479/how-can-i-find-out-if-i-have-xcode-commandline-tools-installed 
# https://stackoverflow.com/questions/25910796/how-to-set-xcode-version-as-default-in-my-mac
